[package]
name = "nss-hyper"
version = "0.4.3"
authors = ["Jed Davis <jld@mozilla.com>"]

[dependencies]
hyper = "0.9.10"
nss = { version = "*", path = ".." }
nss-webpki = { version = "0.2", path = "../nss-webpki" }
time = "0.1.35"
