[package]
name = "nss-hyper"
version = "0.4.8"
authors = ["Jed Davis <jld@mozilla.com>"]

[dependencies]
hyper = { version = "0.9.10", default_features = false }
nss = { version = "0.7.0", path = ".." }
nss-webpki = { version = "0.3", path = "../nss-webpki" }
time = "0.1.35"
