[package]
name = "nss-hyper"
version = "0.4.7"
authors = ["Jed Davis <jld@mozilla.com>"]

[dependencies]
hyper = "0.9.10"
nss = { version = "0.7.0", path = ".." }
nss-webpki = { version = "0.3", path = "../nss-webpki" }
time = "0.1.35"
